window.DefinePanel('Georgia', {author: 'Mordred', version: '2.0.0', features: {drag_n_drop: true} });

include(fb.ProfilePath + '\\georgia\\js\\polyfills.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\js_marc2003\\js\\lodash.min.js');
include(fb.ProfilePath + '\\georgia\\js\\helpers.js');
include(fb.ProfilePath + '\\georgia\\js\\hyperlinks.js');
include(fb.ProfilePath + '\\georgia\\js\\timeline.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Common.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Utility_LinkedList.js');
include(fb.ProfilePath + '\\georgia\\js\\globals.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Control_ContextMenu.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Control_HtaMsgBox.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Control_HtaGroupPresetsMngr.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Control_Scrollbar.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Control_List.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Panel_Playlist.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Panel_Library.js');
include(fb.ProfilePath + '\\georgia\\js\\CaTRoX_QWR\\Control_Button.js');
include(fb.ProfilePath + '\\georgia\\js\\color.js');
include(fb.ProfilePath + '\\georgia\\js\\themes.js');
include(fb.ProfilePath + '\\georgia\\js\\volume.js');
include(fb.ProfilePath + '\\georgia\\js\\image-caching.js');
include(fb.ProfilePath + '\\georgia\\js\\ui-components.js');
include(fb.ProfilePath + '\\georgia\\js\\georgia-main.js');
include(fb.ProfilePath + '\\georgia\\js\\lyrics.js');